### ISSUE TITLE
Q: Did you start from VS2015?

### ISSUE THREAD

**Issue by mwpowellhtx** [amis92/RecordGenerator#29]
Hello,

Not a question re: ``RecordGenerator`` itself, per se, but more the *Visual Studio migration path*. Did you start from ``VS2015`` and migrate into ``VS2017``? Or did you begin from ``VS2017`` from scratch?

I've got a couple of projects in a solution that I am faced with such a migration path, and I wonder how best to do it in order to leverage ``CodeGeneration.Roslyn``, much the same way as you did, in order to auto-generate some very boilerplate partial classes, overloaded operators, and so on.

Thanks!

**Comment by amis92** [comment]
I've adopted VS2017 before I've even used CodeGeneration.Roslyn for this project (early on it's been based purely on Roslyn Analyzer+CodeFix extensibility model).

I can advise to target NETStandard 2.0 with any library you have when migrating to VS2017/SDK-csproj model, it's pretty much all you need, compatible with .NET Framework 4.6.1. So when all your libraries are NS2.0, you can use them in any application targeting net461.

That said, I've got no experience in migrating big solutions, just some of my personal ones, and for these it was quite often a rewrite because of the shiny new thing I've seen or other distraction :D

**Comment by mwpowellhtx** [comment]
@amis92 I appreciate the response. Yes, much of this *.NET Standard* shiny new thing is what I'm contending with at the moment. Reading community blogs, etc, I gather that's much of the distraction.

I ended up "parking" a the old projects in an "old" state, and "recapturing" the code in new *.NET Standard 2.0* projects. It is early days making this leap as far as I'm concerned, but so far so good, notwithstanding a couple of tooling misconceptions. Mostly to do with nuances of NuGet package references conflicting with tooling team assumptions.

Oh, for growing pains, I suppose.

Cheers, thanks again!

**Comment by mwpowellhtx** [comment]
Thanks for the feedback, and thank you for the insights at any rate.
