### ISSUE TITLE
Which Standard to target

### ISSUE THREAD

**Issue by mwpowellhtx** [amis92/RecordGenerator#33]
Revisiting this after my initial digestion of the shift to ``.NET Standard``/``Core`` in my library of interest. Q: Do I need to target ``.NET Standard 1.x``? Or can I target ``2.x``? Or even both?

**Comment by amis92** [comment]
That depends about which project you ask about.

This solution contains three separate building blocks, Generator, Attributes, Analyzers. Analyzers support in Roslyn has scarce documentation, so I didn't exepriment much. Attributes can target as low as netstandard 1.0 I believe. Generators have to be 1.6+ since last update to CodeGeneration.Roslyn because of taking dependency on Microsoft.Extensions.DependecyModel or similar.

But all that is not really that important, as Analyzers and Generators don't have any impact on available targets for the library you'll use them in. What I mean is that these are strictly development dependencies that only run during compilation/development phase.

So, your Generator project must target netstandard1.6, but the project where code will be generated, say MyProject.GeneratedCode, can target net45, netstandard 1.3, 1.0, netcoreapp1.0/2.0, anything really. The only limiting factor is that MyProject.GeneratedCode must be SDK-style csproj-based.

**Comment by mwpowellhtx** [comment]
> ``Analyzers`` support in ``Roslyn`` has scarce documentation...

As I've discovered.

> Generators have to be 1.6+ since last update to ``CodeGeneration.Roslyn`` because of taking dependency on ``Microsoft.Extensions.DependecyModel`` or similar.

Good to know. So, I could ostensibly allow my generator project to drive consistent ``.NET Standard`` dependencies?

> These are strictly development dependencies that only run during compilation/development phase ... but the project where code will be generated, say ``MyProject.GeneratedCode``, can target ...

Yes, I get that.

> The only limiting factor is that ``MyProject.GeneratedCode`` must be SDK-style csproj-based.

Not really sure why that is, but I'd like to understand it better. Working through my analyzers, generators, etc, I will learn it, though.

Anywho, if I learn anything interesting, I'll circle around.

Cheers.

**Comment by amis92** [comment]
Yeah, Generator project can use any `netstandard1.6`+ dependencies.

The reason for requiring SDK-style csproj is because `CodeGeneration.Roslyn.Tools` is packaged as `DotNetCliTool` named `dotnet-codegen` and only this new SDK project type supports using this kind of tools. It's the direction everything move to, with support for migrating `packages.config` into SDK-csproj now included in VS2017 v15.7.

Overall the whole code generation framework built by AArnott (CodeGeneration.Roslyn) is built around that new SDK/DotNetCli tooling.
